apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment2
  namespace: nodeappdemo
  labels:
    app: nodeapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodeapp2
  template:
    metadata:
      labels:
        app: nodeapp2 
    spec:
      containers:
      - name: nodeserver2
        image: srimankiwi/nodeapp:latest
        ports:
        - containerPort: 4000
          hostPort: 31111
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service2
spec:
  selector:
    app: nodeapp2
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 4000
    nodePort: 31111
